# Generated by Django 5.0 on 2024-05-05 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'db_table': 'subject',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='relationalUserSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academico.subject')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('surname', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academico.rol')),
                ('subject', models.ManyToManyField(through='Academico.relationalUserSubject', to='Academico.subject')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'user',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='relationalusersubject',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academico.user'),
        ),
        migrations.AlterUniqueTogether(
            name='relationalusersubject',
            unique_together={('user', 'subject')},
        ),
    ]
